### PR TITLE
fix for extension removing color scheme

### LINKED ISSUE #2: Extension is removing color scheme/theme
https://gitduck.com/watch/5d9c668cca64e141675dc718

Reproduce with this settings:

```
"workbench.activityBar.visible": false,
    "workbench.colorCustomizations": {
        "activityBar.background": "#111",
        "editor.background": "#000",
        "editor.lineHighlightBackground": "#333",
        "editorGroupHeader.tabsBackground": "#111",
        "editorIndentGuide.background": "#111",
        "editorLineNumber.activeForeground": "#fff",
        "editorWidget.background": "#111",
        "panel.background": "#111",
        "peekViewEditor.background": "#111",
        "sideBar.background": "#111",
        "sideBar.foreground": "#fff",
        "sideBarSectionHeader.background": "#000",
        "statusBar.background": "#111",
        "tab.activeBackground": "#000",
        "tab.inactiveBackground": "#111",
        "titleBar.activeBackground": "#111"
    },
    "workbench.colorTheme": "Atom One Dark",
    "workbench.editor.enablePreview": false,
    "workbench.editor.highlightModifiedTabs": true,
    "workbench.fontAliasing": "antialiased",
    "workbench.iconTheme": "vscode-icons",
    "workbench.startupEditor": "welcomePage",
```

With GitDuck it becomes:

```
{
    "workbench.activityBar.visible": false,
    "workbench.colorTheme": "Atom One Dark",
    "workbench.editor.enablePreview": false,
    "workbench.editor.highlightModifiedTabs": true,
    "workbench.fontAliasing": "antialiased",
    "workbench.iconTheme": "vscode-icons",
    "workbench.startupEditor": "welcomePage",
  }
```

### PR DESCRIPTION
**Pull request by m-henderson**
This pr fixes #2 

**Test PR**
1. debug the extension and set your default settings to the settings listed in #2 . 
2. start a git duck stream and notice that the users styles are still applied but the color of the status bar changes to indicate a live GitDuck Stream. 
3. Stop the gitduck stream and notice that the users color settings are reserved and set back to what they were.

### CODE REVIEW

File: src/status.ts [hunk 1]
```diff
@@ -15,9 +15,22 @@ class StatusBar {
...
     timeout: NodeJS.Timer | null = null;
     counting = false;
+    userColorCustomizations: any;
+    gitDuckColorCustomizations: any;
 
     constructor() {
+        const statusBarFGColor = '#802525';
+        const statusBarBGColor = '#F85246';
         this.item = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right);
+        this.userColorCustomizations = workbenchConfig.get('colorCustomizations');
```
Comment (drag0s) [inline src/status.ts:23]: I'd store the `userColorCustomizations` in the `start()` method (which is called when the user starts recording). Else, users may still lose color scheme changes if changed with the GitDuck extension installed because we'd restore the outdated `userColorCustomizations`.

**Comment by drag0s** [comment]
Reviewing the PR and some code suggestions https://gitduck.com/watch/5da5a4ff951a393524f21c1d
